quotes = dict()

quotes['AAPL'] = {'quoteSummary': {'error': '',
                  'result': [{'price': {'averageDailyVolume10Day': {},
                                        'averageDailyVolume3Month': {},
                                        'circulatingSupply': {},
                                        'currency': 'USD',
                                        'currencySymbol': '$',
                                        'exchange': 'NMS',
                                        'exchangeDataDelayedBy': 0,
                                        'exchangeName': 'NasdaqGS',
                                        'fromCurrency': 'null',
                                        'lastMarket': 'null',
                                        'longName': 'Apple Inc.',
                                        'marketCap': {'fmt': '2.66T',
                                                      'longFmt': '2,655,211,749,376.00',
                                                      'raw': 2655211749376},
                                        'marketState': 'PRE',
                                        'maxAge': 1,
                                        'openInterest': {},
                                        'postMarketChange': {'fmt': '-0.59',
                                                             'raw': -0.58999634},
                                        'postMarketChangePercent': {'fmt': '-0.36%',
                                                                    'raw': -0.0036455533},
                                        'postMarketPrice': {'fmt': '161.25',
                                                            'raw': 161.25},
                                        'postMarketSource': 'DELAYED',
                                        'postMarketTime': 1638579600,
                                        'preMarketChange': {'fmt': '0.72',
                                                            'raw': 0.7200012},
                                        'preMarketChangePercent': {'fmt': '0.44%',
                                                                   'raw': 0.004448846},
                                        'preMarketPrice': {'fmt': '162.56',
                                                           'raw': 162.56},
                                        'preMarketSource': 'FREE_REALTIME',
                                        'preMarketTime': 1638786850,
                                        'priceHint': {'fmt': '2',
                                                      'longFmt': '2',
                                                      'raw': 2},
                                        'quoteSourceName': 'Nasdaq Real Time '
                                                           'Price',
                                        'quoteType': 'EQUITY',
                                        'regularMarketChange': {'fmt': '-1.92',
                                                                'raw': -1.9199982},
                                        'regularMarketChangePercent': {'fmt': '-1.17%',
                                                                       'raw': -0.011724464},
                                        'regularMarketDayHigh': {'fmt': '164.96',
                                                                 'raw': 164.96},
                                        'regularMarketDayLow': {'fmt': '159.72',
                                                                'raw': 159.72},
                                        'regularMarketOpen': {'fmt': '164.02',
                                                              'raw': 164.02},
                                        'regularMarketPreviousClose': {'fmt': '163.76',
                                                                       'raw': 163.76},
                                        'regularMarketPrice': {'fmt': '161.84',
                                                               'raw': 161.84},
                                        'regularMarketSource': 'FREE_REALTIME',
                                        'regularMarketTime': 1638565204,
                                        'regularMarketVolume': {'fmt': '118.02M',
                                                                'longFmt': '118,023,116.00',
                                                                'raw': 118023116},
                                        'shortName': 'Apple Inc.',
                                        'strikePrice': {},
                                        'symbol': 'AAPL',
                                        'toCurrency': 'null',
                                        'underlyingSymbol': 'null',
                                        'volume24Hr': {},
                                        'volumeAllCurrencies': {}}}]}}

quotes['BABA'] = {'quoteSummary': {'error': 'null',
                  'result': [{'price': {'averageDailyVolume10Day': {},
                                        'averageDailyVolume3Month': {},
                                        'circulatingSupply': {},
                                        'currency': 'USD',
                                        'currencySymbol': '$',
                                        'exchange': 'NYQ',
                                        'exchangeDataDelayedBy': 0,
                                        'exchangeName': 'NYSE',
                                        'fromCurrency': 'null',
                                        'lastMarket': 'null',
                                        'longName': 'Alibaba Group Holding '
                                                    'Limited',
                                        'marketCap': {'fmt': '332.32B',
                                                      'longFmt': '332,315,197,440.00',
                                                      'raw': 332315197440},
                                        'marketState': 'PRE',
                                        'maxAge': 1,
                                        'openInterest': {},
                                        'postMarketChange': {'fmt': '-0.41',
                                                             'raw': -0.40999603},
                                        'postMarketChangePercent': {'fmt': '-0.37%',
                                                                    'raw': -0.003661987},
                                        'postMarketPrice': {'fmt': '111.55',
                                                            'raw': 111.55},
                                        'postMarketSource': 'DELAYED',
                                        'postMarketTime': 1638579598,
                                        'preMarketChange': {'fmt': '2.04',
                                                            'raw': 2.040001},
                                        'preMarketChangePercent': {'fmt': '1.82%',
                                                                   'raw': 0.0182208},
                                        'preMarketPrice': {'fmt': '114.00',
                                                           'raw': 114.0},
                                        'preMarketSource': 'FREE_REALTIME',
                                        'preMarketTime': 1638787699,
                                        'priceHint': {'fmt': '2',
                                                      'longFmt': '2',
                                                      'raw': 2},
                                        'quoteSourceName': 'Nasdaq Real Time '
                                                           'Price',
                                        'quoteType': 'EQUITY',
                                        'regularMarketChange': {'fmt': '-10.04',
                                                                'raw': -10.040001},
                                        'regularMarketChangePercent': {'fmt': '-8.23%',
                                                                       'raw': -0.08229509},
                                        'regularMarketDayHigh': {'fmt': '118.19',
                                                                 'raw': 118.19},
                                        'regularMarketDayLow': {'fmt': '108.70',
                                                                'raw': 108.7},
                                        'regularMarketOpen': {'fmt': '118.00',
                                                              'raw': 118.0},
                                        'regularMarketPreviousClose': {'fmt': '122.00',
                                                                       'raw': 122.0},
                                        'regularMarketPrice': {'fmt': '111.96',
                                                               'raw': 111.96},
                                        'regularMarketSource': 'DELAYED',
                                        'regularMarketTime': 1638565296,
                                        'regularMarketVolume': {'fmt': '70.27M',
                                                                'longFmt': '70,266,474.00',
                                                                'raw': 70266474},
                                        'shortName': 'Alibaba Group Holding '
                                                     'Limited',
                                        'strikePrice': {},
                                        'symbol': 'BABA',
                                        'toCurrency': 'null',
                                        'underlyingSymbol': 'null',
                                        'volume24Hr': {},
                                        'volumeAllCurrencies': {}}}]}}
quotes['GOOG'] = {'quoteSummary': {'error': 'null',
                  'result': [{'price': {'averageDailyVolume10Day': {},
                                        'averageDailyVolume3Month': {},
                                        'circulatingSupply': {},
                                        'currency': 'USD',
                                        'currencySymbol': '$',
                                        'exchange': 'NMS',
                                        'exchangeDataDelayedBy': 0,
                                        'exchangeName': 'NasdaqGS',
                                        'fromCurrency': 'null',
                                        'lastMarket': 'null',
                                        'longName': 'Alphabet Inc.',
                                        'marketCap': {'fmt': '1.89T',
                                                      'longFmt': '1,888,407,912,448.00',
                                                      'raw': 1888407912448},
                                        'marketState': 'PRE',
                                        'maxAge': 1,
                                        'openInterest': {},
                                        'postMarketChange': {'fmt': '-0.41',
                                                             'raw': -0.4099121},
                                        'postMarketChangePercent': {'fmt': '-0.01%',
                                                                    'raw': -0.00014380812},
                                        'postMarketPrice': {'fmt': '2,850.00',
                                                            'raw': 2850.0},
                                        'postMarketSource': 'DELAYED',
                                        'postMarketTime': 1638579593,
                                        'preMarketChange': {'fmt': '-8.51',
                                                            'raw': -8.51001},
                                        'preMarketChangePercent': {'fmt': '-0.30%',
                                                                   'raw': -0.002985539},
                                        'preMarketPrice': {'fmt': '2,841.90',
                                                           'raw': 2841.9},
                                        'preMarketSource': 'FREE_REALTIME',
                                        'preMarketTime': 1638787829,
                                        'priceHint': {'fmt': '2',
                                                      'longFmt': '2',
                                                      'raw': 2},
                                        'quoteSourceName': 'Nasdaq Real Time '
                                                           'Price',
                                        'quoteType': 'EQUITY',
                                        'regularMarketChange': {'fmt': '-25.12',
                                                                'raw': -25.120117},
                                        'regularMarketChangePercent': {'fmt': '-0.87%',
                                                                       'raw': -0.008735822},
                                        'regularMarketDayHigh': {'fmt': '2,904.26',
                                                                 'raw': 2904.26},
                                        'regularMarketDayLow': {'fmt': '2,823.00',
                                                                'raw': 2823.0},
                                        'regularMarketOpen': {'fmt': '2,889.91',
                                                              'raw': 2889.91},
                                        'regularMarketPreviousClose': {'fmt': '2,875.53',
                                                                       'raw': 2875.53},
                                        'regularMarketPrice': {'fmt': '2,850.41',
                                                               'raw': 2850.41},
                                        'regularMarketSource': 'FREE_REALTIME',
                                        'regularMarketTime': 1638565204,
                                        'regularMarketVolume': {'fmt': '1.33M',
                                                                'longFmt': '1,334,374.00',
                                                                'raw': 1334374},
                                        'shortName': 'Alphabet Inc.',
                                        'strikePrice': {},
                                        'symbol': 'GOOG',
                                        'toCurrency': 'null',
                                        'underlyingSymbol': 'null',
                                        'volume24Hr': {},
                                        'volumeAllCurrencies': {}}}]}}

quotes['TSLA'] = {'quoteSummary': {'error': 'null',
                  'result': [{'price': {'averageDailyVolume10Day': {},
                                        'averageDailyVolume3Month': {},
                                        'circulatingSupply': {},
                                        'currency': 'USD',
                                        'currencySymbol': '$',
                                        'exchange': 'NMS',
                                        'exchangeDataDelayedBy': 0,
                                        'exchangeName': 'NasdaqGS',
                                        'fromCurrency': 'null',
                                        'lastMarket': 'null',
                                        'longName': 'Tesla, Inc.',
                                        'marketCap': {'fmt': '1.02T',
                                                      'longFmt': '1,019,293,728,768.00',
                                                      'raw': 1019293728768},
                                        'marketState': 'PRE',
                                        'maxAge': 1,
                                        'openInterest': {},
                                        'postMarketChange': {'fmt': '-6.97',
                                                             'raw': -6.9699707},
                                        'postMarketChangePercent': {'fmt': '-0.69%',
                                                                    'raw': -0.006867169},
                                        'postMarketPrice': {'fmt': '1,008.00',
                                                            'raw': 1008.0},
                                        'postMarketSource': 'DELAYED',
                                        'postMarketTime': 1638579600,
                                        'preMarketChange': {'fmt': '-11.74',
                                                            'raw': -11.73999},
                                        'preMarketChangePercent': {'fmt': '-1.16%',
                                                                   'raw': -0.011566835},
                                        'preMarketPrice': {'fmt': '1,003.23',
                                                           'raw': 1003.23},
                                        'preMarketSource': 'FREE_REALTIME',
                                        'preMarketTime': 1638788402,
                                        'priceHint': {'fmt': '2',
                                                      'longFmt': '2',
                                                      'raw': 2},
                                        'quoteSourceName': 'Nasdaq Real Time '
                                                           'Price',
                                        'quoteType': 'EQUITY',
                                        'regularMarketChange': {'fmt': '-69.63',
                                                                'raw': -69.630005},
                                        'regularMarketChangePercent': {'fmt': '-6.42%',
                                                                       'raw': -0.06419879},
                                        'regularMarketDayHigh': {'fmt': '1,090.58',
                                                                 'raw': 1090.5753},
                                        'regularMarketDayLow': {'fmt': '1,000.21',
                                                                'raw': 1000.21},
                                        'regularMarketOpen': {'fmt': '1,084.79',
                                                              'raw': 1084.79},
                                        'regularMarketPreviousClose': {'fmt': '1,084.60',
                                                                       'raw': 1084.6},
                                        'regularMarketPrice': {'fmt': '1,014.97',
                                                               'raw': 1014.97},
                                        'regularMarketSource': 'FREE_REALTIME',
                                        'regularMarketTime': 1638565203,
                                        'regularMarketVolume': {'fmt': '30.52M',
                                                                'longFmt': '30,516,306.00',
                                                                'raw': 30516306},
                                        'shortName': 'Tesla, Inc.',
                                        'strikePrice': {},
                                        'symbol': 'TSLA',
                                        'toCurrency': 'null',
                                        'underlyingSymbol': 'null',
                                        'volume24Hr': {},
                                        'volumeAllCurrencies': {}}}]}}